terraform-validate:
  runs-on: ubuntu-latest
  needs: [lint, test]
  steps:
    - uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.0.0"

    - name: Terraform Init
      run: |
        cd infrastructure
        terraform init -backend=false

    - name: Terraform Format
      run: |
        cd infrastructure
        terraform fmt -check

    - name: Terraform Validate
      run: |
        cd infrastructure
        terraform validate
